name: CI Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate a build step
        run: |
          echo "Building the project..."
          sleep 5
          echo "Done."

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Job - ${{ job.status }}
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,

            The CI job for repository ${{ github.repository }} has completed.
            🔹 Branch: ${{ github.ref_name }}
            🔹 Status: ${{ job.status }}
            🔹 Commit: ${{ github.sha }}

            View workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -- GitHub Actions Bot
