name: CI Email, SMS & WhatsApp Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate a build step
        run: |
          echo "Building the project..."
          sleep 5
          echo "Done."

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ GitHub Actions Workflow - ${{ job.status }}"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            -------------------------------------------------------
            ✅ GitHub Actions Workflow Notification
            -------------------------------------------------------

            Repository:  ${{ github.repository }}
            Branch:      ${{ github.ref_name }}
            Commit SHA:  ${{ github.sha }}
            Status:      ${{ job.status }}

            Workflow Run URL:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -------------------------------------------------------
            This is an automated message from your GitHub Actions.

      - name: Send SMS & WhatsApp Notification
        if: always()
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_SMS_FROM: ${{ secrets.TWILIO_SMS_FROM }}
          SMS_TO: ${{ secrets.SMS_TO }}
          WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          pip install twilio

          echo 'import os' > notify.py
          echo 'from twilio.rest import Client' >> notify.py
          echo '' >> notify.py
          echo 'client = Client(os.environ["TWILIO_ACCOUNT_SID"], os.environ["TWILIO_AUTH_TOKEN"])' >> notify.py
          echo '' >> notify.py
          echo 'message_body = f"""' >> notify.py
          echo '✅ GitHub Actions Notification' >> notify.py
          echo 'Repo: {os.environ["GITHUB_REPOSITORY"]}' >> notify.py
          echo 'Branch: {os.environ["GITHUB_REF_NAME"]}' >> notify.py
          echo 'Commit: {os.environ["GITHUB_SHA"][:7]}' >> notify.py
          echo 'Status: {os.environ["JOB_STATUS"]}' >> notify.py
          echo '🔗 https://github.com/{os.environ["GITHUB_REPOSITORY"]}/actions/runs/{os.environ["GITHUB_RUN_ID"]}' >> notify.py
          echo '"""' >> notify.py
          echo '' >> notify.py
          echo '# Send SMS' >> notify.py
          echo 'sms = client.messages.create(' >> notify.py
          echo '    body=message_body,' >> notify.py
          echo '    from_=os.environ["TWILIO_SMS_FROM"],' >> notify.py
          echo '    to=os.environ["SMS_TO"]' >> notify.py
          echo ')' >> notify.py
          echo 'print("SMS sent:", sms.sid)' >> notify.py
          echo '' >> notify.py
          echo '# Send WhatsApp' >> notify.py
          echo 'whatsapp = client.messages.create(' >> notify.py
          echo '    body=message_body,' >> notify.py
          echo '    from_=os.environ["WHATSAPP_FROM"],' >> notify.py
          echo '    to=os.environ["WHATSAPP_TO"]' >> notify.py
          echo ')' >> notify.py
          echo 'print("WhatsApp sent:", whatsapp.sid)' >> notify.py
          python notify.py
