name: CI Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate build
        run: |
          echo "Building project..."
          sleep 5
          echo "Build completed."

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ GitHub Actions Workflow - ${{ job.status | toUpperCase }}"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            -------------------------------------------------------
            ✅ GitHub Actions Workflow Notification
            -------------------------------------------------------

            Repository:  ${{ github.repository }}
            Branch:      ${{ github.ref_name }}
            Commit SHA:  ${{ github.sha }}
            Status:      ${{ job.status }}
            Duration:    ${{ job.duration || 'N/A' }}

            Workflow Run URL:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -------------------------------------------------------
            This is an automated message from your GitHub Actions.
