name: CI Email and WhatsApp Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate a build step
        run: |
          echo "Building the project..."
          sleep 5
          echo "Done."

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ GitHub Actions Workflow - ${{ job.status }}"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            -------------------------------------------------------
            ✅ GitHub Actions Workflow Notification
            -------------------------------------------------------

            Repository:  ${{ github.repository }}
            Branch:      ${{ github.ref_name }}
            Commit SHA:  ${{ github.sha }}
            Status:      ${{ job.status }}

            Workflow Run URL:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -------------------------------------------------------
            This is an automated message from your GitHub Actions.

      - name: Send WhatsApp Notification
        if: always()
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          pip install twilio

          echo 'import os' > send_whatsapp.py
          echo 'from twilio.rest import Client' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo 'client = Client(os.environ["TWILIO_ACCOUNT_SID"], os.environ["TWILIO_AUTH_TOKEN"])' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo 'msg = f"""' >> send_whatsapp.py
          echo '✅ GitHub Actions Notification' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo 'Repository: {os.environ["GITHUB_REPOSITORY"]}' >> send_whatsapp.py
          echo 'Branch: {os.environ["GITHUB_REF_NAME"]}' >> send_whatsapp.py
          echo 'Commit: {os.environ["GITHUB_SHA"][:7]}' >> send_whatsapp.py
          echo 'Status: {os.environ["JOB_STATUS"]}' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo '🔗 Run: https://github.com/{os.environ["GITHUB_REPOSITORY"]}/actions/runs/{os.environ["GITHUB_RUN_ID"]}' >> send_whatsapp.py
          echo '"""' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo 'message = client.messages.create(' >> send_whatsapp.py
          echo '    body=msg,' >> send_whatsapp.py
          echo '    from_=os.environ["TWILIO_WHATSAPP_FROM"],' >> send_whatsapp.py
          echo '    to=os.environ["WHATSAPP_TO"]' >> send_whatsapp.py
          echo ')' >> send_whatsapp.py
          echo '' >> send_whatsapp.py
          echo 'print("WhatsApp Message SID:", message.sid)' >> send_whatsapp.py

          python send_whatsapp.py


            - name: Send SMS Notification
        if: always()
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_SMS_FROM: ${{ secrets.TWILIO_SMS_FROM }}
          SMS_TO: ${{ secrets.SMS_TO }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          pip install twilio

          echo 'import os' > send_sms.py
          echo 'from twilio.rest import Client' >> send_sms.py
          echo '' >> send_sms.py
          echo 'client = Client(os.environ["TWILIO_ACCOUNT_SID"], os.environ["TWILIO_AUTH_TOKEN"])' >> send_sms.py
          echo '' >> send_sms.py
          echo 'msg = f"""' >> send_sms.py
          echo '✅ GitHub Actions Notification' >> send_sms.py
          echo 'Repo: {os.environ["GITHUB_REPOSITORY"]}' >> send_sms.py
          echo 'Branch: {os.environ["GITHUB_REF_NAME"]}' >> send_sms.py
          echo 'Commit: {os.environ["GITHUB_SHA"][:7]}' >> send_sms.py
          echo 'Status: {os.environ["JOB_STATUS"]}' >> send_sms.py
          echo '🔗 https://github.com/{os.environ["GITHUB_REPOSITORY"]}/actions/runs/{os.environ["GITHUB_RUN_ID"]}' >> send_sms.py
          echo '"""' >> send_sms.py
          echo '' >> send_sms.py
          echo 'message = client.messages.create(' >> send_sms.py
          echo '    body=msg,' >> send_sms.py
          echo '    from_=os.environ["TWILIO_SMS_FROM"],' >> send_sms.py
          echo '    to=os.environ["SMS_TO"]' >> send_sms.py
          echo ')' >> send_sms.py
          echo '' >> send_sms.py
          echo 'print("SMS Message SID:", message.sid)' >> send_sms.py

          python send_sms.py

